function plotboxbetweenpoints(R,r1,r2,jointfc,linkec,jointfc1)
[x0,y0,z0]=box2P(R,[r1(1),r1(2),r1(3)],[r2(1),r2(2),r2(3)]);
s=surf(x0,y0,z0,'FaceColor',jointfc,'Facealpha',0.6, ...
'EdgeColor',linkec,'AmbientStrength',0.6);
c = s.CData;
s.CDataMapping = 'direct';
patch('Vertices',[x0(1,:)' y0(1,:)' z0(1,:)'], ...
'Faces',[1:5],'FaceColor','none', ...
'EdgeColor','none','AmbientStrength',0.6);
patch('Vertices',[x0(2,:)' y0(2,:)' z0(2,:)'], ...
'Faces',[1:5],'FaceColor','none', ...
'EdgeColor','none','AmbientStrength',0.6);
% patch('Vertices',[x0(1,3)' y0(1,3)' z0(1,3)'], ...
% 'Faces',2,'FaceColor',jointfc1, ...
% 'EdgeColor','none','AmbientStrength',0.6);
end